version: "3.9"
services:
  reader:
    build:
      context: ./DataStorageReader
      dockerfile: ./Dockerfile
    ports: 
      - "5000:5000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
  
  writer:
    build:
      context: ./DataStorageWriter
      dockerfile: ./Dockerfile
    ports: 
      - "5100:5100"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5100

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "./.localstack:/tmp/localstack"
